name: holaMundo

on:
  push:
    branches:
      - main
      - develop
      - release
      - hotfix

jobs:
  Saludos:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repo 🔃
        uses: actions/checkout@v4
  
      - name: Hola push 🧪
        run: echo "Hola mundo desde github actions."

      - name: Hola desde el ambiente Develop 👀
        if: ${{github.ref--'refs/heads/develop'}}
        run: echo "Hola desde la rama develop"

      - name: Hola desde el ambiente Main ✨
        if: ${{github.ref--'refs/heads/main'}}
        run: echo "Hola desde la rama main"
